#!/usr/bin/env ansible-playbook
# create-instance.yml

# Example usage: ansible-playbook create-instance.yml
---

- name: Create EC2 instance
  hosts: localhost
  vars_files: vars.yml

  tasks:

# ----- GET IDS OF EXISTING OBJECTS

    - name: Get Security Group ID
      amazon.aws.ec2_security_group_info:
        filters:
          'tag:Project': '{{ project_name }}'
      register: sg_result

    - name: Store VPC and Security Group ID
      ansible.builtin.set_fact:
        group_id: '{{ sg_result.security_groups[0].group_id }}'
        vpc_id: '{{ sg_result.security_groups[0].vpc_id }}'

    - name: Get Subnet ID
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: '{{ vpc_id }}'
          availability-zone: '{{ availability_zone }}'
      register: subnet_result

    - name: Store VPC and Security Group ID
      ansible.builtin.set_fact:
        subnet_id: '{{ subnet_result.subnets[0].subnet_id }}'


# ----- CREATE INSTANCE

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: '{{ item }}'
        region: '{{ region }}'
        vpc_subnet_id: '{{ subnet_id }}'
        key_name: '{{ key_name }}'
        instance_type: '{{ instance.instance_type }}'
        security_groups:
          - '{{ group_id }}'
          - default
        image_id: '{{ instance.image_id }}'
        network: '{{ instance.network }}'
        volumes: '{{ instance.volumes }}'
        tags: '{{ org_tags | combine(project_tags) }}'
        state: started
        wait: true
        wait_timeout: 120
      loop: '{{ server_names }}'
      register: instance_result

    - name: Print summary about instance cretion
      ansible.builtin.debug:
        msg: |
          [✔]  Instance created.
          [ℹ]  Instance name:   {{ instance_result | json_query("results[*].instances[0].tags.Name") | join(", ") }}
          [ℹ]  Instance ID:     {{ instance_result | json_query("results[*].instances[0].instance_id") | join(", ") }}
          [ℹ]  Instance type:   {{ instance_result.results[0].instances[0].instance_type }}
          [ℹ]  State:           {{ instance_result | json_query("results[*].instances[0].state.name") | join(", ") }}
          [ℹ]  Tags:            {{ instance_result.results[0].instances[0].tags | to_nice_yaml }}
      when: instance_result.changed
