#!/usr/bin/env ansible-playbook
# create-security.yml

# Example usage: ansible-playbook create-security.yml
---

- name: Create Security Group
  hosts: localhost
  vars_files: vars.yml

  tasks:

    - name: Get VPC ID
      amazon.aws.ec2_vpc_net_info:
        filters:
          'tag:Project': '{{ project_name }}'
      register: vpc_result

    - name: Store VPC ID
      ansible.builtin.set_fact:
        vpc_id: '{{ vpc_result.vpcs[0].id }}'

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: '{{ project_name }} - SG'
        description: '{{ project_name }} Security Group'
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: 'Allow all on port 22'
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: 'Allow all on port 80'
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
            rule_desc: 'Allow all on port 443'
        vpc_id: '{{ vpc_id }}'
        tags: '{{ org_tags | combine(project_tags) }}'
      # register: sg_result
