#!/usr/bin/env ansible-playbook
# get-node-info.yml
---
- name: Get node info
  hosts: all
  remote_user: root

  tasks:

    - name: Print inventory info
      debug:
        msg: |
          - All hosts the play should run: {{ ansible_play_hosts_all | to_yaml }}
          - All hosts the play will acutally run: {{ ansible_play_batch | to_yaml }}
          - Inventory hostname (hostname from inventory): {{ inventory_hostname }}
          - Host (FQDN or IP from inventory): {{ ansible_host }}

    - name: Print OS info
      debug:
        msg: |
          - Nodename (fully qualified hostname from system): {{ ansible_nodename }}
          - Hostname (unqualified hostname from system): {{ ansible_hostname }}
          - IP addreses: {{ ansible_all_ipv4_addresses | to_yaml }}
          - Ansible default IP address: {{ ansible_default_ipv4.address }}
          - OS Family: {{ ansible_os_family }}
          - Distribution: {{ ansible_distribution }}
          - Major version: {{ ansible_distribution_major_version }}
          - Release: {{ ansible_distribution_release }}
          - Distribution Version: {{ ansible_distribution_version }}
          - Kernel: {{ ansible_kernel }}
          - Architecture: {{ ansible_architecture }}
          - CPU: {{ ansible_processor | to_yaml }}
          - CPU Core: {{ ansible_processor_cores }}
          - RAM: {{ ansible_memtotal_mb }}
          - SWAP: {{ ansible_memory_mb.swap.total }}
          - Ansible user: {{ ansible_user | default(lookup('env', 'USER')) }}
          - User's home dir: {{ ansible_user_dir }}
          - Package manager: {{ ansible_pkg_mgr }}
