#!/usr/bin/env ansible-playbook
# deploy-lets-encrypt
# Example usage:
#  ansible-playbook deploy-lets-encrypt.yml

---
- name: Deploy Let's Encrypt Issuers for Ingress-NGINX
  hosts: localhost

  vars:
    email: petr.kunc@gmail.com

  tasks:

    - name: Deploy Let's Encrypt Staging and Production Issuer
      kubernetes.core.k8s:
        state: present
        template:
          - path: 'templates/cert-manager/cluster-issuer-staging.yml'
          - path: 'templates/cert-manager/cluster-issuer-prod.yml'



    # - name: Deploy Ingress-NGINX
    #   kubernetes.core.helm:
    #     name: ingress-nginx
    #     chart_ref: ingress-nginx/ingress-nginx
    #     release_namespace: ingress-nginx
    #     create_namespace: true
    #     atomic: true
