#!/usr/bin/env ansible-playbook
# deploy-longhorn.yml

# Example usage:
#  ansible-playbook deploy-longhorn.yml -i server.example.com,
# Do not forget the comma (,) in the inventory paramter (-i)!

---
- name: Deploy Longhorn
  hosts: all
  strategy: linear

  tasks:

    - name: Install required packages
      become: true
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      loop:
        - gawk
        - epel-release
        - jq
        - iscsi-initiator-utils
        - nfs-utils

    - name: Configure iscsi
      become: true
      ansible.builtin.shell:
        cmd: 'echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi'
      register: iscsi_result
      changed_when: iscsi_result.rc != 0

    - name: Start service iscsid and enable for autostart
      become: true
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: true

    - name: Add helm repo
      run_once: true
      delegate_to: localhost
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Deploy Longhorn
      run_once: true
      delegate_to: localhost
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        atomic: true
        values:
          persistence:
            defaultClassReplicaCount: 1
