#!/usr/bin/env ansible-playbook
# deploy-cert-manager.yml

# Example usage:
#  ansible-playbook deploy-cert-manager.yml

---
- name: Deploy cert-manager
  hosts: localhost

  tasks:

    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Deploy cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        atomic: true
        values:
          installCRDs: true
