#!/usr/bin/env ansible-playbook
# deploy-lets-encrypt

# Example usage:
#  ansible-playbook deploy-lets-encrypt.yml

---
- name: Deploy Let's Encrypt Issuers for Ingress-NGINX
  hosts: localhost

  vars:
    email: petr.kunc@gmail.com

  tasks:

    - name: Deploy Let's Encrypt Staging and Production Issuer
      kubernetes.core.k8s:
        state: present
        template:
          - path: 'templates/cert-manager/cluster-issuer-staging.yml'
          - path: 'templates/cert-manager/cluster-issuer-prod.yml'
