#!/usr/bin/env ansible-playbook
# fetch-kubeconfig.yml

# Example usage:
#    Download kube config file from a remote server
#      ansible-playbook fetch-kubeconfig -i server.example.com,
# Do not forget the comma (,) in the inventory paramter (-i)!
---

- name: Download kube config files from RKE2 Server
  hosts: servers

  tasks:

    - name: 'Download kube config file from the server {{ ansible_host }}'
      become: true
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: '~/.kube/{{ ansible_host }}.yml'
        flat: true

    - name: 'Replace default values in downloaded files with hostname: {{ ansible_host }}'
      ansible.builtin.replace:
        path: '~/.kube/{{ ansible_host }}.yml'
        regexp: '{{ item }}'
        replace: '{{ ansible_host }}'
      loop:
        - 'default'
        - '127.0.0.1'
      delegate_to: localhost
