---
all:
  hosts:
  children:
    servers:
      hosts:
        kube1:
          ansible_host: kube1.hcltechsw.academy
    agents:
      hosts:
        kube2:
          ansible_host: kube2.hcltechsw.academy
