#!/usr/bin/env ansible-playbook
# gather-info.yml

# Example usage: 
#  ansible-playbook gather-info.yml -i server.example.com,
# Do not forget the comma (,) in the inventory paramter (-i)!

---
- name: Gather info
  hosts: all

  tasks:
    - name: Print inventory and OS info
      ansible.builtin.debug:
        msg: |
          INFO FROM INVENTORY:
          - All hosts the play should run: {{ ansible_play_hosts_all | to_yaml }}
          - All hosts the play will acutally run: {{ ansible_play_batch | to_yaml }}
          - Inventory hostname (hostname from inventory): {{ inventory_hostname }}
          - Host (FQDN or IP from inventory): {{ ansible_host }}
          - Local Ansible user: {{ ansible_user | default(lookup('env', 'USER')) }}

          INFO FROM OS:
          - Nodename (fully qualified hostname from system): {{ ansible_nodename }}
          - Hostname (unqualified hostname from system): {{ ansible_hostname }}
          - FQDN (from system): {{ ansible_fqdn }}
          - IP addreses: {{ ansible_all_ipv4_addresses | to_yaml }}
          - Ansible default IP address: {{ ansible_default_ipv4.address }}
          - Remote Ansible user: {{ ansible_user_id }}
          - OS Family: {{ ansible_os_family }}
          - Distribution: {{ ansible_distribution }}
          - Major version: {{ ansible_distribution_major_version }}
          - Release: {{ ansible_distribution_release }}
          - Distribution Version: {{ ansible_distribution_version }}
          - Kernel: {{ ansible_kernel }}
          - Architecture: {{ ansible_architecture }}
          - CPU: {{ ansible_processor | to_yaml }}
          - Number vCPUs: {{ ansible_processor_vcpus }}
          - RAM: {{ ansible_memtotal_mb }}
          - SWAP: {{ ansible_memory_mb.swap.total }}
          - SELinux: {{ ansible_selinux }}
          - User ID (on remote server): {{ ansible_user_id }}
          - User home dir: {{ ansible_user_dir }}
          - User shell: {{ ansible_user_shell }}
          - Package manager: {{ ansible_pkg_mgr }}
          - Mounts: {{ ansible_mounts[0].mount }} ... {{ ansible_mounts[0].size_total | human_readable }}
