apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  namespace: '{{ namespace}}'
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - '{{ web_hostname }}'
    secretName: quickstart-example-tls
  rules:
  - host: '{{ web_hostname }}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80

